---
title: "Group12_Nematodes"
output: html_document
---

```{r}
#install.packages("mapdata")
```


```{r}
library("tidyverse")
library("janitor")
library("naniar")
library("readxl")
library(shiny)
library(shinydashboard)
library(shinythemes)
library(fastmap)
library(leaflet)
library(mapdata)
```

```{r}
nematodes <- read.csv("data/dataset2.txt", header = TRUE, sep = "", stringsAsFactors = FALSE, fill = TRUE)
#this way cleans up the data nicely, can clean it up further and combine more data
```

```{r}
names(nematodes)
```

```{r}
treonis <- read.csv("data/Treonis.csv") %>% clean_names()

```

```{r}
soil <- read_excel("Soil_nematodes_all_data_final_Dryad.xlsx") %>% clean_names()
```


```{r} 
treonis_1 <- treonis %>%  #cleaning up the column names 
  rename_with(~str_replace(.x, "_identified", "")) 
 
```

```{r}
soil <- soil %>%
  replace_with_na_all(condition = ~.x == "NaN") %>%
  mutate(across(ends_with("herbivores"), ~ round(suppressWarnings(as.numeric(.)), 1)))

```

```{r}
treonis_2 <- treonis_1 %>% 
  pivot_longer(cols = 14:27, 
               names_to = "species", 
               values_to = "count")
```

```{r}
treonis_2 <- treonis_2 %>% 
  replace_with_na_all(condition = ~.x == 9999) 

```

```{r}
treonis_2 <- treonis_2 %>% 
  replace_with_na_all(condition = ~.x == "nd") 
```

```{r}
treonis_2 <- treonis_2 %>% #pivoted back because there were too many duplicates from the first pivot
  pivot_wider(names_from = "species", 
              values_from = "count")
```

```{r}
  write.csv(treonis_2, "data/treonis_2.csv", row.names = FALSE)
```



```{r}
names(soil)
```
```{r}
summary(soil)
miss_var_summary(soil)
```



```{r}
soil %>% 
  ggplot(aes(x=p_h, y=elevation))+
  geom_point()+
  geom_smooth(method = lm, se=F)
```

```{r}
library(shiny)

ui <- fluidPage(titlePanel("Nematodes with Soils App"),
                selectInput("x", 
                            "Select X Variable",
                            choices = c("p_h", "conductivity", "temperature"),
                            selected = "p_h"),
                selectInput("y", 
                            "Select Y Variable",
                            choices = c("p_h", "conductivity", "temperature"),
                            selected = "conductivity"),
                plotOutput("ggplot_map")
                
  
)

server <- function(input, output, session) {
  session$onSessionEnded(stopApp)
     output$ggplot_map <- renderPlot({
    # Load USA map data
    usa_map <- map_data("himalays")
    
    # Create the map using ggplot2
    ggplot(usa_map, aes(x = long, y = lat, group = group)) +
      geom_polygon(fill = "lightblue", color = "black") +  # Draws map
      theme_minimal() +
      labs(title = "Map of the USA with ggplot2")
  })
}

shinyApp(ui, server)
```


**Other shiny app option, may need to install certain packages**
```{r}
library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Nematode Dashboard"),
  dashboardSidebar(
    sidebarMenu( #adding to this sidebar menu would be useful for other plots 
      menuItem("Map", tabName = "map", icon = icon("map")),
      menuItem("pH Plot", tabName = "ph_plot", icon = icon("chart-line")),
      menuItem("Moisture Plot", tabName = "moisture_plot", icon = icon("chart-bar"))
    ),
    # Inputs common across tabs
    selectInput("nematode", "Select Trophic Guild(s):", 
                choices = unique(nematode$trophic_guild), 
                selected = unique(nematode$trophic_guild)[1],
                multiple = TRUE),
    sliderInput("pH_range", "Select pH Range:",
                min = min(nematode$p_h, na.rm = TRUE), 
                max = max(nematode$p_h, na.rm = TRUE), 
                value = c(min(nematode$p_h, na.rm = TRUE), max(nematode$p_h, na.rm = TRUE))),
    sliderInput("moisture_range", "Select Moisture Range:",
                min = min(nematode$moisture, na.rm = TRUE), 
                max = max(nematode$moisture, na.rm = TRUE), 
                value = c(min(nematode$moisture, na.rm = TRUE), max(nematode$moisture, na.rm = TRUE))),
     sliderInput("elevation_range", "Select Elevation Range:",
                min = min(nematode$elevation, na.rm = TRUE), 
                max = max(nematode$elevation, na.rm = TRUE), 
                value = c(min(nematode$elevation, na.rm = TRUE), max(nematode$elevation, na.rm = TRUE)))
  ), 
  dashboardBody( #can include more tabs if needed here
    tabItems(
      tabItem(tabName = "map",
              leafletOutput("nematode_map", height = 600)
      ),
      tabItem(tabName = "ph_plot",
              plotOutput("pH_plot", height = 500)
      ),
      tabItem(tabName = "moisture_plot",
              plotOutput("moisture_plot", height = 500)
      )
    )
  )
)
                                  
  
server <- function(input, output, session) {
  
  session$onSessionEnded(stopApp)
  
   # Create a color palette for trophic guilds
  pal <- colorFactor(palette = c("#E41A1C", "#377EB8", "#FF7F00", "#984EA3", "#F1C40F"), 
                   domain = unique(nematode$trophic_guild))
  
  # Filtered data based on user input, only include rows where percent > 0
  filtered_data <- reactive({ #this is for the map 
    nematode %>%
      filter(trophic_guild %in% input$nematode,
             elevation >= input$elevation_range[1] & elevation <= input$elevation_range[2],
             p_h >= input$pH_range[1] & p_h <= input$pH_range[2],
             moisture >= input$moisture_range[1] & moisture <= input$moisture_range[2],
             percent > 0)
  })
  
  # Interactive Leaflet Map
  output$nematode_map <- renderLeaflet({
    leaflet(filtered_data()) %>%
  addTiles() %>%
  addCircleMarkers(
    ~longitude, ~latitude,
    color = ~pal(trophic_guild),
    fillColor = ~pal(trophic_guild),
    fillOpacity = 0.8,
    popup = ~paste("Site:", site, 
               "<br>Trophic Guild:", trophic_guild, 
               "<br>Percent:", percent,
               "<br>pH:", p_h,
               "<br>Moisture:", moisture,
               "<br>Elevation:", elevation, 
               "<br>Conductivity:", conductivity),
    clusterOptions = markerClusterOptions()
  ) %>%
  addLegend("topright", 
            pal = pal, 
            values = ~trophic_guild,
            title = "Trophic Guild",
            opacity = 1)
  })
  #this scatterplot and boxplot can be changed or can add more plots, make sure to add more tabs too 
  # Scatter Plot: pH vs. Nematode Enrichment Footprint
  output$pH_plot <- renderPlot({
    ggplot(filtered_data(), aes(x = p_h, y = enrichment_footprint, color = trophic_guild)) +
      geom_point() +
      labs(title = "pH vs. Enrichment Footprint", x = "Soil pH", y = "Enrichment Footprint") +
      theme_minimal()
  })
  
  # Boxplot: Moisture vs. Trophic Guild Percentages
  output$moisture_plot <- renderPlot({
    ggplot(filtered_data(), aes(x = trophic_guild, y = moisture, fill = trophic_guild)) +
      geom_boxplot() +
      labs(title = "Moisture Levels by Trophic Guild", x = "Trophic Guild", y = "Moisture") +
      theme_minimal()
  })
}

shinyApp(ui, server)
```

